# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/DongSky/tutorial/tutorial.cache/wt [current_project]
set_property parent.project_path C:/Users/DongSky/tutorial/tutorial.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/DongSky/tutorial/tutorial.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/DongSky/tutorial/tutorial.srcs/sources_1/imports/Tutorial/tutorial.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/DongSky/tutorial/tutorial.srcs/constrs_1/imports/Tutorial/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/DongSky/tutorial/tutorial.srcs/constrs_1/imports/Tutorial/Nexys4DDR_Master.xdc]


synth_design -top tutorial -part xc7a100tcsg324-1


write_checkpoint -force -noxdef tutorial.dcp

catch { report_utilization -file tutorial_utilization_synth.rpt -pb tutorial_utilization_synth.pb }
